FROM jenkins/jenkins:lts

USER root
RUN apt-get update && apt-get install -y docker.io \
  # cria o grupo docker com o mesmo GID do host e adiciona o jenkins
  && groupmod -g 127 docker \
  && usermod -aG docker jenkins

USER jenkins
